export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_NEWS: 'FETCH_NEWS',
  SUBMIT: 'SUBMIT',
  UPVOTE: 'UPVOTE',
};
